Repository vtex/styleguide, pull requests merged in 2018-12, with the labels that each got.

#439 Add PageBlock component
  CHANGELOG.md
  react/components/PageBlock/README.md
  react/components/PageBlock/index.js
  styleguide.config.js
Labels: Design Done, New Component

#437 Add Layout component
  CHANGELOG.md
  manifest.json
  package.json
  react/Layout.js
  react/components/Layout/README.md
  react/components/Layout/index.js
  react/components/Table/README.md
  styleguide.config.js
Labels: Designing, Developing

#464 Feature/simple conditions
  .eslintrc
  CHANGELOG.md
  docs/components_experimental.md
  package.json
  react/Conditions.js
  react/EXPERIMENTAL_Conditions.js
  react/IconCalendar.js
  react/Toast.js
  react/components/EXPERIMENTAL_Conditions/Atoms/ObjectAtom.js
  react/components/EXPERIMENTAL_Conditions/Atoms/SubjectAtom.js
  react/components/EXPERIMENTAL_Conditions/Atoms/VerbAtom.js
  react/components/EXPERIMENTAL_Conditions/README.md
  react/components/EXPERIMENTAL_Conditions/Separator.js
  react/components/EXPERIMENTAL_Conditions/Statement.js
  react/components/EXPERIMENTAL_Conditions/StrategySelector.js
  react/components/EXPERIMENTAL_Conditions/index.js
  styleguide.config.js
Labels: New Component
