Repository vtex/styleguide, pull requests merged in 2018-05, with the labels that each got.

#129 Feature/checkbox
  CHANGELOG.md
  src/components/Checkbox/README.md
  src/components/Checkbox/index.js
  src/components/icon/BoldCheck/index.js
  src/components/icon/README.md
  styleguide-visual/Checkbox_1_desktop.png
  styleguide-visual/Checkbox_2_desktop.png
  styleguide-visual/Icons_1_desktop.png
Labels: enhancement

#132 Fix/radio click area
  CHANGELOG.md
  src/components/Checkbox/README.md
  src/components/Checkbox/index.js
  src/components/Radio/README.md
  src/components/Radio/index.js
Labels: bug

#126 Feature/empty state
  CHANGELOG.md
  docs/introduction.md
  src/components/EmptyState/README.md
  src/components/EmptyState/index.js
Labels: hold

#128 Fix/card
  CHANGELOG.md
  package.json
  src/components/Card/README.md
  src/components/Card/index.js
  styleguide-visual/Card_2_desktop.png
Labels: hold
