Repository vtex/styleguide, pull requests merged in 2019-10, with the labels that each got.

#820 Add Bulk Actions to EXPERIMENTAL_TableV2
  CHANGELOG.md
  manifest.json
  package.json
  react/EXPERIMENTAL_useTableBulkActions.ts
  react/components/EXPERIMENTAL_Table/BulkActions.tsx
  react/components/EXPERIMENTAL_Table/Checkbox.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
  react/components/EXPERIMENTAL_Table/Pagination.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/Styled.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/ButtonGroup.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/Container.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/InputCustom.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/InputSearch.tsx
  react/components/EXPERIMENTAL_Table/constants.ts
  react/components/EXPERIMENTAL_Table/context.ts
  react/components/EXPERIMENTAL_Table/errors.ts
  react/components/EXPERIMENTAL_Table/hooks/useTableBulkActions.tsx
  react/components/EXPERIMENTAL_Table/index.tsx
  react/components/EXPERIMENTAL_Table/typings.d.ts
Labels: ✨ Enhancement

#863 Experimental Table Tree Checkboxes
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/BulkActions.tsx
  react/components/EXPERIMENTAL_Table/Checkbox.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Loading.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
  react/components/EXPERIMENTAL_Table/DataTable/index.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/Styled.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/ButtonColumns.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/ButtonDensity.tsx
  react/components/EXPERIMENTAL_Table/context.ts
  react/components/EXPERIMENTAL_Table/contexts.ts
  react/components/EXPERIMENTAL_Table/hooks/useTableBulkActions.tsx
  react/components/EXPERIMENTAL_Table/hooks/useTableContext.ts
  react/components/EXPERIMENTAL_Table/index.tsx
  react/components/EXPERIMENTAL_Table/typings.d.ts
  react/components/EXPERIMENTAL_TableTree/README.md
  react/components/EXPERIMENTAL_TableTree/Tree/CellPrefix.tsx
  react/components/EXPERIMENTAL_TableTree/Tree/CollapseToggle.tsx
  react/components/EXPERIMENTAL_TableTree/Tree/TreeHeadings.tsx
  react/components/EXPERIMENTAL_TableTree/Tree/index.tsx
  react/components/EXPERIMENTAL_TableTree/__tests__/checkboxesUtils.test.ts
  react/components/EXPERIMENTAL_TableTree/contexts.tsx
  react/components/EXPERIMENTAL_TableTree/hooks/checkboxesUtils.ts
  react/components/EXPERIMENTAL_TableTree/hooks/useTableTreeCheckboxes.tsx
  react/components/EXPERIMENTAL_TableTree/hooks/useTreeState.ts
  react/components/EXPERIMENTAL_TableTree/index.tsx
  react/components/EXPERIMENTAL_TableTree/sampleData.ts
Labels: ✨ Enhancement

#882 Fix Tooltip popup's position
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Tooltip/TooltipPopup.tsx
Labels: 🐛 Bug

#885 Added checked prop to EXPERIMENTAL_useTableTreeCheckboxes
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_TableTree/README.md
  react/components/EXPERIMENTAL_TableTree/hooks/useTableTreeCheckboxes.tsx
Labels: ✨ Enhancement

#889 Fix: Table tree not rendering if checkboxes are not allowed
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/DataTable/index.tsx
  react/components/EXPERIMENTAL_TableTree/README.md
  react/components/EXPERIMENTAL_TableTree/Tree/CellPrefix.tsx
  react/components/EXPERIMENTAL_TableTree/Tree/TreeHeadings.tsx
  react/components/EXPERIMENTAL_TableTree/Tree/index.tsx
  react/components/EXPERIMENTAL_TableTree/contexts.tsx
  react/components/EXPERIMENTAL_TableTree/index.tsx
Labels: 🐛 Bug

#892 Fix FilterBar statements defaultProps
  CHANGELOG.md
  manifest.json
  package.json
  react/components/FilterBar/index.js
Labels: 🐛 Bug, 🚧 Hold

#883 Fixes hover colors of tertiaries
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Button/index.js
Labels: 🐛 Bug

#895 Make Select accept an array of options as the defaultValue
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Select/index.js
Labels: 🐛 Bug

#896 Fix/add multiple default values proptype 8.x
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Select/index.js
Labels: 🐛 Bug

#893 Fix verb atom behavior when there's only one option
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Statement/Atoms/ObjectAtom.tsx
  react/components/Statement/Atoms/VerbAtom.tsx
  react/components/Statement/index.tsx
Labels: 🐛 Bug

#898 Fix Table v1 SSR errors
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Table/BulkActions.js
  react/components/Table/SimpleTable.js
  react/components/Table/index.js
  react/package.json
  react/yarn.lock
Labels: 🐛 Bug

#899 [8.x] Fix SSR checking in Table
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Table/index.js
Labels: 🐛 Bug

#870 Add vtex-tachyons mention in non-io docs
  CHANGELOG.md
  docs/developing.md
  manifest.json
  package.json
Labels: 📝 Documentation

#891 Allow grouping conditions subject
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Conditions/README.md
  react/components/Conditions/index.tsx
  react/components/EXPERIMENTAL_Select/README.md
  react/components/EXPERIMENTAL_Select/index.js
  react/components/Statement/Atoms/ObjectAtom.tsx
  react/components/Statement/Atoms/SubjectAtom.tsx
  react/components/Statement/Atoms/VerbAtom.tsx
  react/components/Statement/index.tsx
  react/components/Statement/typings.d.ts
Labels: ✨ Enhancement

#921 Fix EXPERIMENTAL_Table toolbar's alignment
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/Toolbar/ButtonGroup.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/Container.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/index.tsx
  react/components/EXPERIMENTAL_Table/constants.ts
Labels: 🐛 Bug
