Repository vtex/styleguide, pull requests merged in 2019-12, with the labels that each got.

#950 Add page top indicator option to Pagination
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Pagination/PageIndicator.js
  react/components/Pagination/index.js
  react/components/Table/SwitchablePagination.js
  react/components/Table/index.js
Labels: ✨ Enhancement

#948 EXPERIMENTAL_useCheckboxTree hook
  CHANGELOG.md
  manifest.json
  package.json
  react/EXPERIMENTAL_useCheckboxTree.ts
  react/EXPERIMENTAL_useTableBulkActions.ts
  react/EXPERIMENTAL_useTableTreeCheckboxes.ts
  react/components/EXPERIMENTAL_Table/BulkActions.tsx
  react/components/EXPERIMENTAL_Table/DataTable/CellPrefix.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/hooks/useTableBulkActions.tsx
  react/components/EXPERIMENTAL_Table/index.tsx
  react/components/EXPERIMENTAL_TableTree/README.md
  react/components/EXPERIMENTAL_TableTree/Tree/Node.tsx
  react/components/EXPERIMENTAL_TableTree/Tree/TreeHeadings.tsx
  react/components/EXPERIMENTAL_TableTree/Tree/index.tsx
  react/components/EXPERIMENTAL_TableTree/hooks/checkboxesUtils.ts
  react/components/EXPERIMENTAL_TableTree/hooks/useTableTreeCheckboxes.tsx
  react/components/EXPERIMENTAL_TableTree/index.tsx
  react/components/EXPERIMENTAL_useCheckboxTree/__tests__/util.test.ts
  react/components/EXPERIMENTAL_useCheckboxTree/constants.ts
  react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
  react/components/EXPERIMENTAL_useCheckboxTree/reducer.ts
  react/components/EXPERIMENTAL_useCheckboxTree/types.ts
  react/components/EXPERIMENTAL_useCheckboxTree/util.ts
Labels: ✨ Enhancement, 🐛 Bug

#955 Compound Bulk Actions
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/BulkActions.tsx
  react/components/EXPERIMENTAL_Table/BulkActions/Actions.tsx
  react/components/EXPERIMENTAL_Table/BulkActions/Tail.tsx
  react/components/EXPERIMENTAL_Table/BulkActions/index.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/constants.ts
  react/components/EXPERIMENTAL_Table/hooks/useTableLineActions.tsx
  react/components/EXPERIMENTAL_Table/index.tsx
  react/components/EXPERIMENTAL_Table/sampleData.ts
  react/components/EXPERIMENTAL_useCheckboxTree/constants.ts
  react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
Labels: ✨ Enhancement

#961 Fix hooks errors on EXPERIMENTAL_Table
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
Labels: 🐛 Bug

#967 Added useTableProportion hook
  CHANGELOG.md
  manifest.json
  package.json
  react/EXPERIMENTAL_useTableProportion.ts
  react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/hooks/useTableProportion.ts
Labels: ✨ Enhancement, 🐛 Bug

#970 Fix buttons
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Button/README.md
  react/components/Button/index.js
Labels: 🐛 Bug

#947 Deprecate UNSAFE_CustomInput in favor of using AutoCompleteInput on EXPERIMENTAL_Table
  CHANGELOG.md
  manifest.json
  package.json
  react/components/AutocompleteInput/index.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/Toolbar/InputAutocomplete.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/InputCustom.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/index.tsx
Labels: ✨ Enhancement

#972 Control checkbox disable state on EXPERIMENTAL_useCheckboxTree
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/sampleData.ts
  react/components/EXPERIMENTAL_useCheckboxTree/README.md
  react/components/EXPERIMENTAL_useCheckboxTree/__tests__/util.test.ts
  react/components/EXPERIMENTAL_useCheckboxTree/constants.ts
  react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
  react/components/EXPERIMENTAL_useCheckboxTree/reducer.ts
  react/components/EXPERIMENTAL_useCheckboxTree/types.ts
  react/components/EXPERIMENTAL_useCheckboxTree/util.ts
  styleguide.config.js
Labels: ✨ Enhancement
