Repository vtex/styleguide, pull requests merged in 2019-07, with the labels that each got.

#702 Add CODEOWNERS
  CHANGELOG.md
  CODEOWNERS
  manifest.json
  package.json
Labels: ✨ Enhancement, 🧹Housekeeping

#713 Fix/date picker known issues
  CHANGELOG.md
  manifest.json
  package.json
  react/components/DatePicker/README.md
  react/components/DatePicker/index.js
  react/yarn.lock
  yarn.lock
Labels: 🐛Bug

#670 Add Link component
  CHANGELOG.md
  manifest.json
  package.json
  react/Link.js
  react/components/Link/README.md
  react/components/Link/index.js
  styleguide.config.js
  yarn.lock
Labels: 🎨 Design Done, 💻 Developing...

#725 Disable component specific codeowners
  CODEOWNERS
Labels: 🧹Housekeeping

#721 Feature/editor icons 8x
  CHANGELOG.md
  manifest.json
  package.json
  react/IconBold.js
  react/IconImage.js
  react/IconItalic.js
  react/IconOrderedList.js
  react/IconText.js
  react/IconUnderline.js
  react/IconUnorderedList.js
  react/components/Textarea/index.js
  react/components/icon/Bold/index.js
  react/components/icon/Image/index.js
  react/components/icon/Italic/index.js
  react/components/icon/OrderedList/index.js
  react/components/icon/Text/index.js
  react/components/icon/Underline/index.js
  react/components/icon/UnorderedList/index.js
Labels: ✨ Enhancement

#726 Add break-word on label
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Radio/index.js
Labels: ✨ Enhancement

#728 Fix/search table selection itens
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Table/Toolbar.js
  react/components/Table/index.js
Labels: 🐛 Bug

#594 Add TimePicker component
  CHANGELOG.md
  manifest.json
  package.json
  react/TimePicker.js
  react/components/DatePicker/README.md
  react/components/DatePicker/index.js
  react/components/DatePicker/react-datepicker.global.css
  react/components/TimePicker/README.md
  react/components/TimePicker/index.js
  styleguide.config.js
  yarn.lock
Labels: 🆕 New Component
