Repository vtex/styleguide, pull requests merged in 2019-09, with the labels that each got.

#783 Table V2 Pagination
  CHANGELOG.md
  manifest.json
  package.json
  react/EXPERIMENTAL_Table.ts
  react/components/EXPERIMENTAL_Table/Pagination.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/SimpleTable/index.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/Container.tsx
  react/components/EXPERIMENTAL_Table/constants.ts
  react/components/EXPERIMENTAL_Table/index.tsx
Labels: ✨ Enhancement

#782 Add the Tooltip component
  CHANGELOG.md
  manifest.json
  package.json
  react/Tooltip.ts
  react/components/Button/index.js
  react/components/Tooltip/Portal.tsx
  react/components/Tooltip/README.md
  react/components/Tooltip/TooltipPopup.tsx
  react/components/Tooltip/hooks.ts
  react/components/Tooltip/index.tsx
  react/components/Tooltip/tooltip.css
  react/components/Tooltip/utils/dom.ts
  react/components/utils/react.ts
  react/package.json
  react/yarn.lock
  styleguide.config.js
Labels: ✨ Enhancement

#814 Fix tsconfig module resolution to be node and not classic
  CHANGELOG.md
  manifest.json
  package.json
  react/tsconfig.json
Labels: 🐛 Bug

#821 Added loading to EXPERIMENTAL_TableV2
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/SimpleTable/Loading.tsx
  react/components/EXPERIMENTAL_Table/SimpleTable/index.tsx
  react/components/EXPERIMENTAL_Table/errors.ts
  react/components/EXPERIMENTAL_Table/hooks/useTableContext.ts
  react/components/EXPERIMENTAL_Table/index.tsx
  react/components/EXPERIMENTAL_Table/typings.d.ts
Labels: ✨ Enhancement

#811 Add import to deprecation Alert
  CHANGELOG.md
  manifest.json
  package.json
  react/components/MultiSelect/README.md
Labels: 🐛 Bug

#812 Add ButtonColumns to EXPERIMENTAL_TABLE_V2
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/SimpleTable/Header.tsx
  react/components/EXPERIMENTAL_Table/SimpleTable/Row.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/ButtonColumns.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/ButtonGroup.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/Menu/Box.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/Menu/Item.tsx
  react/components/EXPERIMENTAL_Table/constants.ts
  react/components/EXPERIMENTAL_Table/hooks/useHiddenColumns.ts
  react/components/EXPERIMENTAL_Table/hooks/useTableState.ts
  react/components/EXPERIMENTAL_Table/typings.d.ts
Labels: ✨ Enhancement, 🎨 Design Needed!

#832 Do not show column for showing/hiding when there is to text
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Table/Toolbar.js
Labels: ✨ Enhancement

#842 Set Tooltip z-index to avoid being shadowed by other components
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Modal/index.js
  react/components/Tooltip/TooltipPopup.tsx
  react/components/utils/zIndex.ts
Labels: 🐛 Bug

#833 Add the autocomplete input component
  CHANGELOG.md
  manifest.json
  package.json
  react/AutocompleteInput.ts
  react/components/AutocompleteInput/Option.tsx
  react/components/AutocompleteInput/README.md
  react/components/AutocompleteInput/SearchInput/index.tsx
  react/components/AutocompleteInput/hooks.ts
  react/components/AutocompleteInput/index.tsx
  styleguide.config.js
Labels: ✨ Enhancement

#834 EXPERIMENTAL_TableV2 Clickable Rows
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/Styled.tsx
  react/components/EXPERIMENTAL_Table/index.tsx
  react/components/EXPERIMENTAL_Table/typings.d.ts
Labels: ✨ Enhancement

#837 EXPERIMENTAL_TABLEV2 Line Actions
  CHANGELOG.md
  manifest.json
  package.json
  react/EXPERIMENTAL_useTableLineActions.ts
  react/components/EXPERIMENTAL_Table/LineActions.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/hooks/useTableLineActions.tsx
  react/components/EXPERIMENTAL_Table/index.tsx
  react/components/EXPERIMENTAL_TableTree/index.tsx
Labels: ✨ Enhancement

#855 Fix EXPERIMENTAL_Table's ButtonNewLine presentation
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/Toolbar/Button.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/ButtonNewLine.tsx
Labels: 🐛 Bug
