Repository vtex/styleguide, pull requests merged in 2019-08, with the labels that each got.

#738 Added IconInfo
  CHANGELOG.md
  manifest.json
  package.json
  react/IconInfo.js
  react/components/Button/index.js
  react/components/ColorPicker/ColorHistory.js
  react/components/icon/Info/index.js
  react/components/icon/README.md
  react/docs/Pathline.js
  react/modules/deprecated.js
Labels: 🆕 New Component

#748 Add printerIcon
  CHANGELOG.md
  manifest.json
  package.json
  react/IconPrinter.js
  react/components/Table/index.js
  react/components/icon/Printer/index.js
  react/components/icon/README.md
Labels: 🆕 New Component

#745 🧪 👨🏾‍💻 Table v2
  CHANGELOG.md
  manifest.json
  package.json
  react/EXPERIMENTAL_Table.ts
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/SimpleTable/Cell.tsx
  react/components/EXPERIMENTAL_Table/SimpleTable/Header.tsx
  react/components/EXPERIMENTAL_Table/SimpleTable/Rows.tsx
  react/components/EXPERIMENTAL_Table/SimpleTable/index.tsx
  react/components/EXPERIMENTAL_Table/constants.ts
  react/components/EXPERIMENTAL_Table/context.ts
  react/components/EXPERIMENTAL_Table/hooks/useTableContext.ts
  react/components/EXPERIMENTAL_Table/hooks/useTableState.ts
  react/components/EXPERIMENTAL_Table/index.tsx
  react/components/EXPERIMENTAL_Table/typings.d.ts
  react/components/EXPERIMENTAL_Table/util.ts
  styleguide.config.js
Labels: 🆕 New Component, 🎨 Design Needed!, 💻 Developing...

#754 Fix/little fixes
  package.json
  react/components/Dropdown/README.md
  react/components/Dropdown/index.js
  react/components/Input/index.js
Labels: ✨ Enhancement, 📝 Documentation

#758 fix toggle onclick bug
  react/components/Toggle/index.js
Labels: 🐛 Bug

#750 Added Toolbar, ButtonGroup and DensityButton to Table v2
  CHANGELOG.md
  manifest.json
  package.json
  react/EXPERIMENTAL_Table.ts
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/SimpleTable/Header.tsx
  react/components/EXPERIMENTAL_Table/SimpleTable/Rows.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/Button.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/ButtonDensity.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/ButtonGroup.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/Container.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/Menu/Box.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/Menu/Item.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/Menu/context.ts
  react/components/EXPERIMENTAL_Table/Toolbar/Menu/index.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/index.tsx
  react/components/EXPERIMENTAL_Table/constants.ts
  react/components/EXPERIMENTAL_Table/hooks/useDensity.ts
  react/components/EXPERIMENTAL_Table/hooks/useOutsideClick.ts
  react/components/EXPERIMENTAL_Table/hooks/useTableState.ts
  react/components/EXPERIMENTAL_Table/index.tsx
  react/components/EXPERIMENTAL_Table/typings.d.ts
  react/components/EXPERIMENTAL_Table/util.ts
Labels: ✨ Enhancement, 🎨 Design Needed!

#756 fix toggle onclick bug
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Toggle/index.js
Labels: 🐛 Bug

#772 Fix Toggle click area
  CHANGELOG.md
  react/components/Toggle/index.js
Labels: 🐛 Bug

#803 Added InputCustom to Table V2
  CHANGELOG.md
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/Toolbar/InputCustom.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/index.tsx
Labels: ✨ Enhancement

#797 Fix radio circle position to items-start
  CHANGELOG.md
  react/components/Radio/index.js
Labels: 🐛 Bug
