Repository vtex/styleguide, pull requests merged in 2019-11, with the labels that each got.

#927 Fix: EXPERIMENTAL_TableTree shows arrow with empty nodesKey
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_TableTree/README.md
  react/components/EXPERIMENTAL_TableTree/Tree/index.tsx
  react/components/EXPERIMENTAL_TableTree/hooks/useTableTreeCheckboxes.tsx
Labels: 🐛 Bug

#874 Feature/table bulk actions deselect lines on input search clear
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Table/README.md
  react/components/Table/Toolbar.js
  react/components/Table/index.js
Labels: 🐛 Bug

#916 Update table height after rendering
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Table/SimpleTable.js
Labels: 🐛 Bug

#922 Provide updateCellMeasurements() method for cell height refresh
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Table/README.md
  react/components/Table/SimpleTable.js
Labels: ✨ Enhancement

#934 Update description for the dynamicRowHeight field
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Table/index.js
Labels: 📝 Documentation

#920 Better table columns and documentation
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/hooks/useTableBulkActions.tsx
  react/components/EXPERIMENTAL_Table/hooks/useTableVisibility.ts
  react/components/EXPERIMENTAL_Table/index.tsx
  react/components/EXPERIMENTAL_TableTree/README.md
  react/components/EXPERIMENTAL_TableTree/Tree/TreeHeadings.tsx
  react/components/EXPERIMENTAL_TableTree/Tree/index.tsx
Labels: 📝 Documentation

#935 Move charts to experimental package
  CHANGELOG.md
  manifest.json
  package.json
  react/LineChart.tsx
  react/components/EXPERIMENTAL_Charts/LineChart/README.md
  react/components/EXPERIMENTAL_Charts/LineChart/constants.ts
  react/components/EXPERIMENTAL_Charts/LineChart/index.tsx
  react/components/EXPERIMENTAL_Charts/LineChart/multilineSample.js
  react/components/EXPERIMENTAL_Charts/LineChart/sampleData.js
  react/components/EXPERIMENTAL_Charts/commonProps.ts
  react/components/EXPERIMENTAL_Charts/helpers.ts
  react/components/EXPERIMENTAL_Charts/typings.d.ts
  styleguide.config.js
Labels: ✨ Enhancement

#940 Table Tree UX Improvements
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
  react/components/EXPERIMENTAL_TableTree/README.md
  react/components/EXPERIMENTAL_TableTree/Tree/CellPrefix.tsx
  react/components/EXPERIMENTAL_TableTree/Tree/CollapseToggle.tsx
  react/components/EXPERIMENTAL_TableTree/Tree/TreeHeadings.tsx
  react/components/EXPERIMENTAL_TableTree/Tree/index.tsx
  react/components/EXPERIMENTAL_TableTree/index.tsx
Labels: ✨ Enhancement, 🐛 Bug

#928 Fix checkbox alignment when there is no arrow in the EXPERIMENTAL_TableTree
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_TableTree/Tree/CellPrefix.tsx
Labels: 🐛 Bug

#946 Fixed first column width of EXPRIMENTAL_TableTree docs
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_TableTree/README.md
Labels: 🐛 Bug
