Repository vtex/styleguide, pull requests merged in 2019-01, with the labels that each got.

#426 Action Menu
  CHANGELOG.md
  manifest.json
  package.json
  react/ActionMenu.js
  react/components/ActionMenu/README.md
  react/components/ActionMenu/index.js
  react/components/Menu/index.js
  styleguide.config.js
Labels: New Component

#484 Add aside prop to pageBlock
  CHANGELOG.md
  manifest.json
  package.json
  react/components/PageBlock/README.md
  react/components/PageBlock/index.js
Labels: Design Needed, Developing

#500 Position Toast to the right
  CHANGELOG.md
  manifest.json
  package.json
  react/Toast.js
  react/ToastConsumer.js
  react/ToastProvider.js
  react/components/ToastProvider/README.md
  react/components/ToastProvider/Toast.js
  react/components/ToastProvider/ToastManager.js
  react/components/ToastProvider/index.js
  react/withToast.js
  styleguide.config.js
Labels: Enhancement

#514 InputCurrency
  CHANGELOG.md
  manifest.json
  package.json
  react/InputCurrency.js
  react/components/Input/README.md
  react/components/InputCurrency/README.md
  react/components/InputCurrency/index.js
  react/package.json
  react/yarn.lock
  styleguide.config.js
  yarn.lock
Labels: New Component
