Repository vtex/styleguide, pull requests merged in 2020-03, with the labels that each got.

#1063 Fix version 1.112.7 in NPM
  CHANGELOG.md
  manifest.json
  package.json
Labels: 🐛 Bug

#1062 Added [COMPOSITION OVER OBJECT PROPS] section at EXPERIMENTAL_Table docs
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/README.md
Labels: 📝 Documentation

#1065 Split EXPERIMENTAL_Table docs on multiple files
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/docs/Components.md
  react/components/EXPERIMENTAL_Table/docs/Features.md
  react/components/EXPERIMENTAL_Table/docs/Introduction.md
  react/components/EXPERIMENTAL_Table/docs/MigrationGuide.md
  react/components/EXPERIMENTAL_Table/docs/Testing.md
  react/components/EXPERIMENTAL_Table/docs/sampleData.ts
  styleguide.config.js
Labels: 📝 Documentation

#1067 Fixed unecessary Cell rerender on EXPERIMENTAL_Table
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/DataTable/Cell.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
Labels: ✨ Enhancement

#1004 Enable headerRenderer usage in all header options
  CHANGELOG.md
  react/components/Table/README.md
  react/components/Table/SimpleTable.js
Labels: 🐛 Bug

#1010 Add size prop to checkbox
  CHANGELOG.md
  react/components/Checkbox/README.md
  react/components/Checkbox/index.js
Labels: ✨ Enhancement

#1077 Add warning icon when input has errorMessage
  CHANGELOG.md
  react/components/Input/index.js
Labels: Next Major, ✨ Enhancement

#1078 Github CI for tests in features branch
  CHANGELOG.md
Labels: ✨ Enhancement

#1095 [FIX] RefError by accessing 'valueLabel' const on Dropdown
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Dropdown/index.js
Labels: 🐛 Bug

#1104 #trivial fixed Dropzone eslint issues
  react/components/Dropzone/index.js
Labels: 🐛 Bug

#1103 fix eslint errors in SelectableCard, Slider and ToastProvider
  react/components/SelectableCard/index.tsx
  react/components/Slider/Selector.js
  react/components/Slider/index.js
  react/components/ToastProvider/Toast.js
  react/components/ToastProvider/ToastManager.js
  react/components/ToastProvider/index.js
Labels: 🐛 Bug

#1079 Tests for EXPERIMENTAL_Table hooks
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Alert/index.test.js
  react/components/Button/index.test.tsx
  react/components/EXPERIMENTAL_Table/hooks/__tests__/useTableMeasures.test.ts
  react/components/EXPERIMENTAL_Table/hooks/__tests__/useTableProportion.test.ts
  react/components/EXPERIMENTAL_Table/hooks/__tests__/useTableSort.test.ts
  react/components/EXPERIMENTAL_Table/hooks/__tests__/useTableVisibility.test.ts
  react/components/EXPERIMENTAL_Table/hooks/useTableMeasures.tsx
  react/components/EXPERIMENTAL_Table/hooks/useTableSort.ts
  setupTests.js
  yarn.lock
Labels: ✨ Enhancement

#1115 Tests for the Tabs component
  CHANGELOG.md
  react/components/Tabs/Tab.js
  react/components/Tabs/index.test.tsx
Labels: ✨ Enhancement
