Repository vtex/styleguide, pull requests merged in 2020-01, with the labels that each got.

#984 Fixed useCheckboxTree hooks dependencies
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
Labels: 🐛 Bug

#991 Return lastToggledItem of EXPERIMENTAL_useCheckboxTree
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
Labels: ✨ Enhancement

#994 EXPERIMENTAL_Table motion
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/BulkActions/index.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Loading.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
  react/components/EXPERIMENTAL_Table/DataTable/index.tsx
  react/components/EXPERIMENTAL_Table/hooks/useTableMotion.ts
  react/components/EXPERIMENTAL_Table/index.tsx
  react/components/EXPERIMENTAL_TableTree/Tree/Node.tsx
  react/components/EXPERIMENTAL_TableTree/index.tsx
Labels: ✨ Enhancement

#997 Add missing handle to the label of the Button
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Button/index.js
Labels: good first issue

#1000 Allow EXPERIMENTAL Items to be sorted
  CHANGELOG.md
  manifest.json
  package.json
  react/EXPERIMENTAL_useTableSort.ts
  react/components/EXPERIMENTAL_Table/DataTable/Cell.tsx
  react/components/EXPERIMENTAL_Table/DataTable/CellPrefix.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
  react/components/EXPERIMENTAL_Table/DataTable/index.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/hooks/useTableLineActions.tsx
  react/components/EXPERIMENTAL_Table/hooks/useTableSort.ts
  react/components/EXPERIMENTAL_Table/index.tsx
  react/components/EXPERIMENTAL_Table/sampleData.ts
  react/components/EXPERIMENTAL_TableTree/Tree/Node.tsx
  react/package.json
  react/yarn.lock
Labels: ✨ Enhancement

#1009 Standardize classnames imports
  react/components/AutocompleteInput/Option.tsx
  react/components/AutocompleteInput/SearchInput/index.tsx
  react/components/EXPERIMENTAL_Table/BulkActions/Actions.tsx
  react/components/EXPERIMENTAL_Table/BulkActions/Tail.tsx
  react/components/EXPERIMENTAL_Table/BulkActions/index.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Cell.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
  react/components/EXPERIMENTAL_Table/DataTable/index.tsx
  react/components/EXPERIMENTAL_Table/FilterBar.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/Button.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/ButtonGroup.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/InputAutocomplete.tsx
  react/components/EXPERIMENTAL_Table/Toolbar/index.tsx
  react/components/Pagination/index.js
  react/components/Totalizer/index.js
Labels: Pattern, 🧹Housekeeping

#1016 Add missing handles from NumericStepper
  CHANGELOG.md
  manifest.json
  package.json
  react/components/NumericStepper/index.js
Labels: good first issue, ✨ Enhancement

#1008 Toolbar buttons default size
  CHANGELOG.md
  manifest.json
  package.json
  react/components/Table/Toolbar.js
Labels: 🐛 Bug
