Repository vtex/styleguide, pull requests merged in 2020-02, with the labels that each got.

#1022 Added ActionBar to EXPERIMENTAL_Table
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/ActionBar.tsx
  react/components/EXPERIMENTAL_Table/BulkActions/index.tsx
  react/components/EXPERIMENTAL_Table/FilterBar.tsx
  react/components/EXPERIMENTAL_Table/Pagination.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/Toolbar/index.tsx
  react/components/EXPERIMENTAL_Table/Totalizer.tsx
  react/components/EXPERIMENTAL_Table/constants.ts
  react/components/EXPERIMENTAL_Table/index.tsx
Labels: ✨ Enhancement

#1024 State handlers Docs
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/hooks/useTableVisibility.ts
  react/components/EXPERIMENTAL_Table/index.tsx
  react/components/EXPERIMENTAL_Table/sampleData.ts
Labels: 📝 Documentation

#1025 Added EXPERIMENTAL_Table features docs
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/README.md
Labels: 📝 Documentation

#1038 LineChart custom configuration possibility
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Charts/BarChart/constants.ts
  react/components/EXPERIMENTAL_Charts/BarChart/index.tsx
  react/components/EXPERIMENTAL_Charts/BubbleChart/index.tsx
  react/components/EXPERIMENTAL_Charts/LineChart/constants.ts
  react/components/EXPERIMENTAL_Charts/LineChart/index.tsx
  react/components/EXPERIMENTAL_Charts/ScatterChart/index.tsx
  react/components/EXPERIMENTAL_Charts/commonProps.ts
  react/components/EXPERIMENTAL_Charts/helpers.ts
  react/components/EXPERIMENTAL_Charts/types.ts
  react/components/EXPERIMENTAL_Charts/typings.d.ts
Labels: ✨ Enhancement

#1039 Change Toast's keepAfterUpdate propType to bool
  CHANGELOG.md
  manifest.json
  package.json
  react/components/ToastProvider/Toast.js
Labels: 🐛 Bug

#1042 Added the highlightOnHover prop to EXPERIMENTAL_Table
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/index.tsx
Labels: ✨ Enhancement

#1047 Added sticky header to EXPERIMENTAL_Table
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/DataTable/Cell.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Rows.tsx
  react/components/EXPERIMENTAL_Table/DataTable/index.tsx
  react/components/EXPERIMENTAL_Table/README.md
  react/components/EXPERIMENTAL_Table/hooks/useTableMotion.ts
  react/components/EXPERIMENTAL_Table/index.tsx
Labels: ✨ Enhancement

#1052 Fixed EXPERIMENTAL_Table background colors
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/DataTable/Cell.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Headings.tsx
  react/components/EXPERIMENTAL_Table/DataTable/Row.tsx
Labels: 🐛 Bug
