Repository vtex/styleguide, pull requests merged in 2020-10, with the labels that each got.

#1330 Fix AutocompleteInput term to follow input.value changes
  CHANGELOG.md
  react/components/AutocompleteInput/index.tsx
Labels: 🐛 Bug

#1331 Add new EXPERIMENTAL_Modal
  CHANGELOG.md
  assets/modal_anatomy.png
  react/EXPERIMENTAL_Modal.ts
  react/components/EXPERIMENTAL_Modal/BottomBar.tsx
  react/components/EXPERIMENTAL_Modal/FocusTrap.tsx
  react/components/EXPERIMENTAL_Modal/README.md
  react/components/EXPERIMENTAL_Modal/TopBar.tsx
  react/components/EXPERIMENTAL_Modal/__snapshots__/index.test.tsx.snap
  react/components/EXPERIMENTAL_Modal/index.test.tsx
  react/components/EXPERIMENTAL_Modal/index.tsx
  react/components/EXPERIMENTAL_Modal/modal.css
  react/components/EXPERIMENTAL_Modal/modal.stories.tsx
  react/components/EXPERIMENTAL_Modal/utils.ts
  react/utilities/useDisclosure/docs.md
  react/utilities/useDisclosure/index.ts
  styleguide.config.js
Labels: ✨ Enhancement

#1337 Update developing.md
  docs/developing.md
  react/components/AutocompleteInput/hooks.ts
  react/components/AutocompleteInput/index.tsx
Labels: 📝 Documentation

#1332 Fixes root checkbox being always checked when all children checkboxes…
  CHANGELOG.md
  react/components/EXPERIMENTAL_useCheckboxTree/index.tsx
Labels: 🐛 Bug

#1339 Fix EXPERIMENTAL_Table emptyState type definitions
  CHANGELOG.md
  manifest.json
  package.json
  react/components/EXPERIMENTAL_Table/context/loading.tsx
  react/components/EXPERIMENTAL_Table/index.tsx
Labels: 🐛 Bug
